# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubSwiftList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubSwiftList
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'

  target 'GitHubSwiftListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitHubSwiftListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
